# typed: false
# frozen_string_literal: true

# This file is generated by the dch release workflow. DO NOT EDIT.
# Lite build: no embedded libghostty-vt terminal mirror (~100 KB).
# --read/--wait are unavailable (exit 3); everything else works.
class DchLite < Formula
  desc "Detachable terminal session manager (lite: no terminal mirror)"
  homepage "https://github.com/ventsislav-georgiev/dch"
  url "https://github.com/ventsislav-georgiev/dch/archive/refs/tags/v1.8.0.tar.gz"
  sha256 "42389161d1f327beffe323600f6644242eba0da6d6b937eb475ddbb1a2030f44"
  license "GPL-2.0-or-later"

  conflicts_with "dch", because: "both install a dch binary"

  def install
    system "./configure", "--without-libghostty"
    system "make"
    bin.install "dch"
    man1.install "dch.1"
  end

  test do
    assert_match "detachable terminal session", shell_output("#{bin}/dch -h")
  end
end
