# typed: false
# frozen_string_literal: true

# This file is generated by the dch release workflow. DO NOT EDIT.
class Dch < Formula
  desc "Detachable terminal sessions with a headless agent API"
  homepage "https://github.com/ventsislav-georgiev/dch"
  url "https://github.com/ventsislav-georgiev/dch/archive/refs/tags/v1.17.2.tar.gz"
  sha256 "514e0663c9b6b290d5f863ca6a6f511244138dfc00f30c6bf69acf035fc7476f"
  license "GPL-2.0-or-later"

  conflicts_with "dch-lite", because: "both install a dch binary"

  def install
    system "./configure"
    system "make"
    bin.install "dch"
    man1.install "dch.1"
  end

  test do
    assert_match "detachable terminal session", shell_output("#{bin}/dch -h")
  end
end
