# typed: false
# frozen_string_literal: true

# This file is generated by the dch release workflow. DO NOT EDIT.
class Dch < Formula
  desc "Detachable terminal sessions with a headless agent API"
  homepage "https://github.com/ventsislav-georgiev/dch"
  url "https://github.com/ventsislav-georgiev/dch/archive/refs/tags/v1.6.0.tar.gz"
  sha256 "99bdaf17bb0c857b8fea11c00e28f9184c9d9080f194bf2408bf0bc6d80df2c0"
  license "GPL-2.0-or-later"

  conflicts_with "dch-lite", because: "both install a dch binary"

  def install
    system "./configure"
    system "make"
    bin.install "dch"
    man1.install "dch.1"
  end

  test do
    assert_match "detachable terminal session", shell_output("#{bin}/dch -h")
  end
end
