# typed: false
# frozen_string_literal: true

# This file is generated by the dch release workflow. DO NOT EDIT.
class Dch < Formula
  desc "Detachable terminal sessions with a headless agent API"
  homepage "https://github.com/ventsislav-georgiev/dch"
  url "https://github.com/ventsislav-georgiev/dch/archive/refs/tags/v1.4.0.tar.gz"
  sha256 "c9a8768c76e05cf2dd8c66431687da2f5971b373c50d468c6832849ff816850a"
  license "GPL-2.0-or-later"

  conflicts_with "dch-lite", because: "both install a dch binary"

  def install
    system "./configure"
    system "make"
    bin.install "dch"
    man1.install "dch.1"
  end

  test do
    assert_match "detachable terminal session", shell_output("#{bin}/dch -h")
  end
end
