# typed: false
# frozen_string_literal: true

# This file is generated by the k9s release workflow. DO NOT EDIT.
class K9s < Formula
  desc "Kubernetes CLI To Manage Your Clusters In Style!"
  homepage "https://k9scli.io/"
  version "0.50.18-custom.13"

  on_macos do
    on_arm do
      url "https://github.com/ventsislav-georgiev/k9s/releases/download/v0.50.18-custom.13/k9s_Darwin_arm64.tar.gz"
      sha256 "85aceaf99fe7dc2b0ac5e38620236ab24c9c8abcff164a1271066f2198f8031e"

      def install
        bin.install "k9s"
      end
    end
  end

  test do
    system "k9s version"
  end
end
